// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           44
// Async Callback (empty):               1
// Total number of exported functions:  46

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    stake
    (
        init => init
        clearContract => clear_contract
        upgrade => upgrade
        togglePause => toggle_pause
        setSftsAllowed => set_sfts_allowed
        removeSftsAllowed => remove_sfts_allowed
        setSftResource => set_sft_resource
        foodFund => food_fund
        beerFund => beer_fund
        woodFund => wood_fund
        stoneFund => stone_fund
        ironFund => iron_fund
        wargearFund => wargear_fund
        stake => stake
        unStake => un_stake
        claimRewards => claim_rewards
        calculateForAnSpecific => calculate_rewards_for_a_specific_sft
        calculateReward => calculate_rewards
        getCollection => collection
        getPause => pause
        getSftsAllowed => sfts_allowed
        getSftStakedAmount => sft_staked_amount
        getSftStakedAt => sft_staked_at
        getSftResource => sft_resource
        getUserFood => user_food
        getUserBeer => user_beer
        getUserWood => user_wood
        getUserStone => user_stone
        getUserIron => user_iron
        getUserWargear => user_wargear
        getUsersStaked => users_staked
        getFoodIdentifier => food_identifier
        getBeerIdentifier => beer_identifier
        getWoodIdentifier => wood_identifier
        getStoneIdentifier => stone_identifier
        getIronIdentifier => iron_identifier
        getWargearIdentifier => wargear_identifier
        getFoodAmount => food_amount
        getBeerAmount => beer_amount
        getWoodAmount => wood_amount
        getStoneAmount => stone_amount
        getIronAmount => iron_amount
        getWargearAmount => wargear_amount
        getSftsStaked => get_sfts_staked
        getUsers => get_users
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
