// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           47
// Async Callback (empty):               1
// Total number of exported functions:  49

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    stake
    (
        togglePause
        setSftsAllowed
        removeSftsAllowed
        setSftEccu
        setSftResource
        eccuFund
        foodFund
        beerFund
        woodFund
        stoneFund
        ironFund
        wargearFund
        withdrawFunds
        stake
        unStake
        claimRewards
        calculateForAnSpecific
        calculateReward
        getCollection
        getPause
        getSftsAllowed
        getSftStakedAmount
        getSftStakedAt
        getSftEccu
        getSftResource
        getUserFood
        getUserBeer
        getUserWood
        getUserStone
        getUserIron
        getUserWargear
        getUsersStaked
        getFoodIdentifier
        getBeerIdentifier
        getWoodIdentifier
        getStoneIdentifier
        getIronIdentifier
        getWargearIdentifier
        getEccuIdentifier
        getEccuAmount
        getFoodAmount
        getBeerAmount
        getWoodAmount
        getStoneAmount
        getIronAmount
        getWargearAmount
        getSftsStaked
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
